global using CalamityMod.Tiles.Ores;
global using CalamityMod.Tiles.SunkenSea;
global using LuneLib;
global using LuneLib.Common.Players.LuneLibPlayer;
global using LuneLib.FlagUtils;
global using LuneLib.TimerUtils;
global using LuneLib.TimerUtils_Terraria;
global using LuneLib.Utilities;
global using static LuneLib.Utilities.Hashsets.HashSets;
global using static LuneLib.Utilities.LuneLibUtils;
global using static LuneLibAssets.Common.SoundClass;
global using LuneWoL.Common.Mod_Player;
global using static LuneWoL.Common.World_Gen.LuneWoL_Gen;
global using LuneWoL.Content.Buffs.DOT;
global using LuneWoL.Core.Config;
global using static LuneWoL.LuneWoL;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Mono.Cecil.Cil;
global using MonoMod.Cil;
global using ReLogic.Utilities;
global using SpiritMod.Items.BossLoot.StarplateDrops;
global using SpiritMod.Items.Sets.BismiteSet;
global using SpiritMod.Items.Sets.CryoliteSet;
global using SpiritMod.Items.Sets.FloranSet;
global using SpiritMod.Items.Sets.GraniteSet;
global using SpiritMod.Items.Sets.MarbleSet;
global using SpiritMod.Items.Sets.SpiritSet;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.IO;
global using System.Reflection;
global using System.Threading.Tasks;
global using Terraria;
global using Terraria.Audio;
global using Terraria.Chat;
global using Terraria.DataStructures;
global using Terraria.GameContent.Biomes;
global using Terraria.GameContent.Events;
global using Terraria.GameContent.Generation;
global using Terraria.ID;
global using Terraria.IO;
global using Terraria.Localization;
global using Terraria.ModLoader;
global using Terraria.ModLoader.Config;
global using Terraria.ModLoader.IO;
global using Terraria.UI;
global using Terraria.WorldBuilding;
global using ThoriumMod.Tiles;
